name: Security

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: taiki-e/install-action@af8167eefce493c60337887d7b96ffbc22df840c # cargo-deny
      - name: Check advisories and licenses
        run: cargo deny --config .github/deny.toml check
        env:
          RUSTC_WRAPPER: ""
